<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { http } from '../api/http';
import type { Room } from '../types';

type MeetingTemplate={id:number;name:string;title:string;description:string;attendeeNames:string;attendeeCount:number;equipment:string};
const router=useRouter();const loading=ref(false);const recommendations=ref<Room[]>([]);const selected=ref<Room>();const templates=ref<MeetingTemplate[]>([]);const templateName=ref('');
const form=reactive({title:'',dateRange:[] as Date[],attendeeCount:4,equipment:[] as string[],attendeeNames:['示例员工'],description:'',repeatWeeks:1});
const canSubmit=computed(()=>selected.value&&form.title&&form.dateRange.length===2&&form.attendeeNames.length>0);
async function recommend(){if(form.dateRange.length!==2)return ElMessage.warning('请先选择完整会议时间');loading.value=true;try{recommendations.value=(await http.get('/rooms/recommend',{params:{startTime:form.dateRange[0].toISOString(),endTime:form.dateRange[1].toISOString(),attendeeCount:form.attendeeCount,equipment:form.equipment.join(',')}})).data;selected.value=recommendations.value[0];if(!recommendations.value.length)ElMessage.warning('当前条件下没有可用会议室')}finally{loading.value=false}}
async function submit(){const {data}=await http.post('/bookings',{title:form.title,description:form.description,roomId:selected.value!.id,attendeeNames:form.attendeeNames,attendeeCount:form.attendeeCount,startTime:form.dateRange[0],endTime:form.dateRange[1],repeatWeeks:form.repeatWeeks});ElMessage.success(data.createdCount>1?`${data.createdCount} 场周期会议已提交审批`:'预约已提交，正在等待管理员审批');router.push('/bookings')}
function applyTemplate(id:number){const item=templates.value.find(x=>x.id===id);if(!item)return;form.title=item.title;form.description=item.description;form.attendeeNames=item.attendeeNames.split(',');form.attendeeCount=item.attendeeCount;form.equipment=item.equipment?item.equipment.split(','):[]}
async function saveTemplate(){if(!templateName.value)return ElMessage.warning('请输入模板名称');await http.post('/bookings/templates',{name:templateName.value,title:form.title,description:form.description,attendeeNames:form.attendeeNames,attendeeCount:form.attendeeCount,equipment:form.equipment});ElMessage.success('会议模板已保存');templateName.value='';templates.value=(await http.get('/bookings/templates/list')).data}
onMounted(async()=>templates.value=(await http.get('/bookings/templates/list')).data);
</script>
<template><div class="page"><div class="page-header"><div><h2>智能会议预约</h2><p>填写会议条件，系统将自动检测冲突并推荐最合适的空间</p></div><el-select placeholder="使用会议模板" style="width:220px" @change="applyTemplate"><el-option v-for="item in templates" :key="item.id" :label="item.name" :value="item.id" /></el-select></div><div class="booking-layout"><section class="panel"><div class="step-title"><b>01</b><div><h3>会议需求</h3><p>会议的基础信息与资源要求</p></div></div><el-form :model="form" label-position="top"><el-form-item label="会议主题" required><el-input v-model="form.title" maxlength="80" show-word-limit placeholder="例如：第三季度产品路线评审" /></el-form-item><el-form-item label="会议时间" required><el-date-picker v-model="form.dateRange" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间" :default-time="[new Date(2000,0,1,9),new Date(2000,0,1,10)]" style="width:100%" /></el-form-item><div class="form-row"><el-form-item label="参会人数" required><el-input-number v-model="form.attendeeCount" :min="1" :max="500" /></el-form-item><el-form-item label="周期预约"><el-select v-model="form.repeatWeeks"><el-option label="仅本次" :value="1"/><el-option label="连续 2 周" :value="2"/><el-option label="连续 4 周" :value="4"/><el-option label="连续 8 周" :value="8"/></el-select></el-form-item></div><el-form-item label="所需设备"><el-select v-model="form.equipment" multiple placeholder="可多选" style="width:100%"><el-option v-for="item in ['投影仪','显示屏','白板','视频会议','音响','无线麦克风']" :key="item" :value="item" /></el-select></el-form-item><el-form-item label="参会人员" required><el-select v-model="form.attendeeNames" multiple filterable allow-create default-first-option placeholder="输入姓名后回车" style="width:100%" /></el-form-item><el-form-item label="会议说明"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="500" show-word-limit /></el-form-item><div class="template-save"><el-input v-model="templateName" placeholder="模板名称"/><el-button @click="saveTemplate">保存为模板</el-button></div><el-button type="primary" size="large" style="width:100%;margin-top:12px" :loading="loading" @click="recommend">智能匹配会议室</el-button></el-form></section>
<section class="panel result"><div class="step-title"><b>02</b><div><h3>推荐结果</h3><p>按设备匹配度与容量利用率排序</p></div></div><div v-if="!recommendations.length" class="placeholder"><div>⌁</div><h4>等待智能匹配</h4><p>填写左侧需求后，系统将在可用资源中进行计算</p></div><template v-else><article v-for="room in recommendations" :key="room.id" class="recommend-card" :class="{active:selected?.id===room.id}" @click="selected=room"><div class="room-line"><div><h4>{{room.name}}</h4><span>{{room.location}} · {{room.capacity}}人 · {{room.openTime}}-{{room.closeTime}}</span></div><div class="recommend-score">{{room.score}}<small>分</small></div></div><div class="tags"><el-tag v-for="e in room.equipment.split(',')" :key="e" size="small" effect="plain">{{e}}</el-tag></div><p>{{room.reason}}</p></article><el-button type="success" size="large" style="width:100%" :disabled="!canSubmit" @click="submit">提交预约申请</el-button></template></section></div></div></template>
<style scoped>.booking-layout{display:grid;grid-template-columns:1fr 1fr;gap:20px;align-items:start}.step-title{display:flex;gap:13px;align-items:center;border-bottom:1px solid #edf0f4;padding-bottom:17px;margin-bottom:20px}.step-title b{width:38px;height:38px;display:grid;place-items:center;border-radius:10px;background:#eaf2ff;color:#3974e8}.step-title h3,.step-title p{margin:0}.step-title p{color:#939daf;font-size:12px;margin-top:4px}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.form-row .el-select{width:100%}.template-save{display:grid;grid-template-columns:1fr auto;gap:8px}.result{min-height:570px}.placeholder{height:420px;display:grid;place-content:center;text-align:center;color:#9aa5b5}.placeholder div{font-size:56px;color:#c5d4e9}.placeholder h4{margin:12px 0 6px;color:#637086}.placeholder p{font-size:12px}.room-line{display:flex;justify-content:space-between}.room-line h4{margin:0 0 5px;font-size:16px}.room-line span{color:#7e8a9d;font-size:12px}.recommend-score small{font-size:11px}.tags{display:flex;gap:5px;margin:12px 0}.recommend-card p{margin:8px 0 0;color:#63806f;font-size:12px}</style>
