<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import dayjs from 'dayjs';
import { ElMessage } from 'element-plus';
import { http } from '../api/http';
import { useAuthStore } from '../stores/auth';
import type { Room } from '../types';

const auth = useAuthStore(); const rooms = ref<Room[]>([]); const dialog = ref(false); const maintenanceDialog = ref(false); const editingId = ref<number>();
const roomForm = reactive({ name:'', location:'', capacity:8, equipment:['投影仪'] as string[], openTime:'08:00', closeTime:'20:00', description:'', active:true });
const maintenance = reactive({ roomId:0, startTime:[] as Date[], reason:'' });
async function load(){ rooms.value=(await http.get('/rooms')).data }
function edit(room?:Room){ editingId.value=room?.id; Object.assign(roomForm, room ? {...room,equipment:room.equipment.split(',')} : {name:'',location:'',capacity:8,equipment:['投影仪'],openTime:'08:00',closeTime:'20:00',description:'',active:true}); dialog.value=true }
async function save(){ if(editingId.value) await http.put(`/rooms/${editingId.value}`,roomForm); else await http.post('/rooms',roomForm); ElMessage.success('会议室信息已保存');dialog.value=false;load() }
function openMaintenance(room:Room){maintenance.roomId=room.id;maintenance.startTime=[];maintenance.reason='';maintenanceDialog.value=true}
async function saveMaintenance(){await http.post(`/rooms/${maintenance.roomId}/maintenance`,{startTime:maintenance.startTime[0],endTime:maintenance.startTime[1],reason:maintenance.reason});ElMessage.success('维护时段已添加');maintenanceDialog.value=false;load()}
onMounted(load);
</script>
<template><div class="page"><div class="page-header"><div><h2>会议室资源</h2><p>统一维护空间容量、开放时间、设备与维护计划</p></div><el-button v-if="auth.isAdmin" type="primary" @click="edit()">+ 新增会议室</el-button></div>
  <div class="room-grid"><article v-for="room in rooms" :key="room.id" class="room-card"><div class="room-top"><span :class="room.active?'open':'closed'">{{room.active?'正常开放':'已停用'}}</span><small>{{room.location}}</small></div><h3>{{room.name}}</h3><p>{{room.description||'暂无说明'}}</p><div class="meta"><span>容纳 <b>{{room.capacity}}</b> 人</span><span>{{room.openTime}} - {{room.closeTime}}</span></div><div class="equipment"><el-tag v-for="item in room.equipment.split(',')" :key="item" size="small" effect="plain">{{item}}</el-tag></div><div v-if="room.maintenance?.length" class="maintenance">最近维护：{{dayjs(room.maintenance[0].startTime).format('MM-DD HH:mm')}} · {{room.maintenance[0].reason}}</div><div v-if="auth.isAdmin" class="actions"><el-button link type="primary" @click="edit(room)">编辑资料</el-button><el-button link @click="openMaintenance(room)">添加维护</el-button></div></article></div>
  <el-dialog v-model="dialog" :title="editingId?'编辑会议室':'新增会议室'" width="570px"><el-form :model="roomForm" label-width="90px"><el-form-item label="会议室名称" required><el-input v-model="roomForm.name" /></el-form-item><el-form-item label="所在位置" required><el-input v-model="roomForm.location" /></el-form-item><el-form-item label="容纳人数"><el-input-number v-model="roomForm.capacity" :min="1" :max="500" /></el-form-item><el-form-item label="配套设备"><el-select v-model="roomForm.equipment" multiple allow-create filterable style="width:100%"><el-option v-for="item in ['投影仪','显示屏','白板','视频会议','音响','无线麦克风']" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="开放时间"><el-time-select v-model="roomForm.openTime" start="06:00" step="00:30" end="22:00" style="width:45%" /><span style="margin:0 10px">至</span><el-time-select v-model="roomForm.closeTime" start="06:30" step="00:30" end="23:00" style="width:45%" /></el-form-item><el-form-item label="说明"><el-input v-model="roomForm.description" type="textarea" /></el-form-item><el-form-item label="状态"><el-switch v-model="roomForm.active" active-text="启用" inactive-text="停用" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  <el-dialog v-model="maintenanceDialog" title="添加维护时段" width="520px"><el-form label-width="80px"><el-form-item label="维护时间" required><el-date-picker v-model="maintenance.startTime" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间" style="width:100%" /></el-form-item><el-form-item label="维护原因" required><el-input v-model="maintenance.reason" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="maintenanceDialog=false">取消</el-button><el-button type="primary" @click="saveMaintenance">确认添加</el-button></template></el-dialog>
</div></template>
<style scoped>.room-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.room-card{background:#fff;border:1px solid #e5eaf2;border-radius:14px;padding:20px;box-shadow:0 5px 22px rgba(31,51,80,.04)}.room-top{display:flex;justify-content:space-between;color:#8995a8}.room-top span{font-size:12px;font-weight:600}.open{color:#29a879}.closed{color:#a0a8b3}.room-card h3{font-size:19px;margin:18px 0 8px}.room-card p{height:39px;color:#8792a4;font-size:13px;line-height:1.6}.meta{display:flex;justify-content:space-between;padding:13px 0;border-top:1px solid #eef1f5;color:#637085;font-size:13px}.equipment{display:flex;gap:6px;flex-wrap:wrap;min-height:25px}.maintenance{margin-top:14px;padding:9px;background:#fff7e9;color:#936616;border-radius:7px;font-size:11px}.actions{margin-top:14px;border-top:1px solid #eef1f5;padding-top:12px}</style>
